name:                stego-minesweeper
version:             0.1.0.0
github:              "eivankin/stego-minesweeper"
license:             BSD3
author:              "Evgenij Ivankin"
maintainer:          "Evgenij Ivankin"
copyright:           "2022 Evgenij Ivankin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/eivankin/stego-minesweeper#readme>

dependencies:
- base >= 4.7 && < 5
- miso

library:
  source-dirs: src

executables:
  stego-minesweeper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stego-minesweeper

tests:
  stego-minesweeper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stego-minesweeper
